# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/brainwalk',
                'doc_host': 'https://TesfaAsmara.github.io',
                'git_url': 'https://github.com/TesfaAsmara/brainwalk',
                'lib_path': 'brainwalk'},
  'syms': {'brainwalk.core': {'brainwalk.core.brainwave': ('core.html#brainwave', 'brainwalk/core.py')}}}