# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['brainwave']

# %% ../nbs/00_core.ipynb 2
def brainwave(vault_dir, transformation, dimensions = 128, window = 10, walk_length = 80, num_walks = 10, workers = 1):
    import obsidiantools.api as otools
    from wirewalk.core import WireWalk

    vault = otools.Vault(vault_dir).connect().gather()

    graph = vault.graph

    # Instantiate a WireWalk object
    wireWalk = WireWalk(graph, dimensions, window, walk_length, num_walks, workers)

    model = wireWalk.fit(transformation)

    return model

